---
- name: Apt install
  block:
  - name: Update all packages on the system
    become: true
    apt:
      upgrade: yes
      update_cache: yes
  - name: Install packages
    apt:
      name:
        - make
        - build-essential
        - git
        - iptables-persistent
      state: present