---
- name: Apt install
  block:
  - name: Install apt-utils
    command: apt update
  - name: Apt upgrade
    command: apt upgrade -y
  - name: Install packages
    apt:
      name:
        - make
        - build-essential
        - git
        - iptables-persistent
      state: present