---
- name: Check if Go is installed
  command: /usr/local/go/bin/go version
  register: go_check
  ignore_errors: true
  changed_when: false

- name: Install Go
  when: go_check.rc != 0
  block:
  - name: Download Go {{ go_package }}
    get_url:
      url: "https://go.dev/dl/{{ go_package }}"
      dest: "/tmp/{{ go_package }}"

  - name: Install Go
    ansible.builtin.unarchive:
      src: "/tmp/{{ go_package }}"
      dest: /usr/local
      remote_src: true

  - name: Add Go to PATH
    lineinfile:
      path: "{{ ansible_env.HOME }}/.bashrc"
      line: 'export PATH=$PATH:/usr/local/go/bin'
      state: present
      create: true

  - name: Remove Go installation archive
    file:
      path: "/tmp/{{ go_package }}"
      state: absent
