---
- name: Check if Go is installed
  command: awg-quick --help
  register: awg_check
  ignore_errors: true
  changed_when: false

- name: Install Amnezia WG
  when: awg_check.rc != 0
  block:
  - name: Clone amneziawg-go repository
    git:
      repo: https://github.com/amnezia-vpn/amneziawg-go
      dest: ~/awg/amneziawg-go
      clone: true
      update: true

  - name: Install amneziawg-go
    command: sudo env PATH=/usr/local/go/bin:{{ ansible_env.PATH }} make install
    args:
      chdir: ~/awg/amneziawg-go

  - name: Clone amneziawg-tools repository
    git:
      repo: https://github.com/amnezia-vpn/amneziawg-tools.git
      dest: ~/awg/amneziawg-tools
      clone: true
      update: true

  - name: Install amneziawg-tools
    command: sudo env PATH=/usr/local/go/bin:{{ ansible_env.PATH }} make install
    args:
      chdir: ~/awg/amneziawg-tools/src
