---
- name: Apt upgrade
  apt:
    update_cache: yes
    upgrade: true
- name: Install packages
  apt:
    name:
      - make
      - build-essential
      - git
      - iptables-persistent
    state: present
- name: Install GO
  include_tasks: install_go.yaml
- name: Install AWG
  include_tasks: install_amneziawg.yaml
- name: Config AWG
  include_tasks: config_amneziawg.yaml
