---
- name: Install prerequisites for AmneziaWG
  ansible.builtin.apt:
    name:
      - software-properties-common
      - python3-launchpadlib
      - gnupg2
      - "linux-headers-{{ ansible_facts.kernel }}"
    state: present
    update_cache: yes
  become: yes

- name: Add Amnezia PPA
  ansible.builtin.apt_repository:
    repo: ppa:amnezia/ppa
    state: present
    update_cache: no
  become: yes

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes

- name: Install AmneziaWG
  ansible.builtin.apt:
    name: amneziawg
    state: present
    update_cache: yes
  become: yes
